version: '3.9'

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    networks:
      - devnet
    environment:
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hibernate_db
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  fruits-app:
    image: fruits-inv-backend:2.8
    ports:
      - "8080:8080"
    networks:
      - devnet
    environment:
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hibernate_db
      - QUARKUS_DATASOURCE_URL = jdbc:postgresql://db:5432/hibernate_db
      - QUARKUS_DATASOURCE_USERNAME = postgres
      - QUARKUS_DATASOURCE_PASSWORD = pgpass
    depends_on:
      db:
        condition: service_healthy


networks:
  devnet:
    name: devnet
    driver: bridge