on:
  push:
    branches:
      - setup
  pull_request:
    branches:
      - setup
  workflow_dispatch:

env:

  # Define environment
  ACTION: "destroy"
  S3_VERSION: "Enabled"
  AWS_REGION: "us-east-1"
  S3_DATABASE_STORAGE: "database"
  SECRETS_NAME: "ec2-secrets"
  REPOSITORY_NAME: "${{ github.event.repository.name }}"
  TERRAFORM_BACKEND_S3_BUCKET_NAME: "quarkusproject-terraform"
  REPOSITORY_URL: "https://github.com/${{ github.repository }}"
  AUTH_GITHUBACTION_WITH_AWS_IAM_ROLE_NAME: "quarkushibernate-githubaction-auth"
  TERRAFORM_BACKEND_STATE_FILE_LOCK_DYANAMODB_TABLE: "terraform-state-lock-dynamodb"

permissions:
  id-token: write

jobs:
  SetupInfrastructure:
    if: github.ref == 'refs/heads/setup'
    runs-on: ubuntu-latest
    environment:
      name: setup

    steps:

      - id: "Checkout"
        name: Checkout repo
        uses: actions/checkout@v3

      - id: GenerateTerraformProviderScript
        name: Generate terraform provider script
        run: |
          echo '''
          terraform {
            required_providers {
              aws = {
                source  = "hashicorp/aws"
                version = "~> 4.0"
              }
            } 
            backend "s3" {
              dynamodb_table = "${{ env.TERRAFORM_BACKEND_STATE_FILE_LOCK_DYANAMODB_TABLE }}"
              bucket         = "${{ env.TERRAFORM_BACKEND_S3_BUCKET_NAME }}-${{ env.AWS_REGION }}-${{ secrets.YOUR_AWS_ACCOUNT_ID }}"
              key            = "setup/terraform.tfstate"
              region         = "${{ env.AWS_REGION }}"
            }
          }
          provider "aws" {
            region = "${{ env.AWS_REGION }}"
            #profile = ""
          }
          ''' >> setup/terraform1/providers.tf

      - id: BuildWithQuarkus
        name: Build with quarkus
        run: ls
        shell: bash